# Generated by Django 2.2 on 2021-10-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_author', models.CharField(max_length=200)),
                ('msg_email', models.EmailField(max_length=200)),
                ('msg_message', models.TextField(max_length=600)),
            ],
        ),
    ]
