# Generated by Django 2.2 on 2021-10-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_hobby_hobby_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_desc',
            field=models.CharField(max_length=300),
        ),
    ]
